##### **Sesión 31 - Programación para Ciencia de Datos 2026-1 - 02 de Diciemre de 2025**

# Filtrado avanzado de datos en Pandas

Crea *5 ejemplos* de filtrado avanzado

In [16]:
import pandas as pd
import random

In [27]:
# DataFrame de Pacientes (Hospital)
pacientes = pd.DataFrame({
    "Nombre": [f"Paciente {chr(65+i)}" for i in range(20)], # Genera Paciente A, B, C...
    "Edad": [random.randint(15, 60) for _ in range(20)],
    "Peso_kg": [random.randint(50, 100) for _ in range(20)],
    "Altura_m": [round(random.uniform(1.50, 1.90), 2) for _ in range(20)],
    "Tipo_Sangre": [random.choice(["O+", "A+", "B-", "AB+"]) for _ in range(20)]
})

pacientes

        Nombre  Edad  Peso_kg  Altura_m Tipo_Sangre
0   Paciente A    21       63      1.74          B-
1   Paciente B    41       97      1.67          B-
2   Paciente C    34       86      1.63          O+
3   Paciente D    21       61      1.78         AB+
4   Paciente E    39       83      1.54          A+
5   Paciente F    34       69      1.58          B-
6   Paciente G    37       65      1.81         AB+
7   Paciente H    49       73      1.56          B-
8   Paciente I    21       97      1.60          A+
9   Paciente J    15      100      1.64          B-
10  Paciente K    23       90      1.57          B-
11  Paciente L    49       63      1.55          A+
12  Paciente M    16       63      1.81          B-
13  Paciente N    24       79      1.73         AB+
14  Paciente O    54       70      1.86         AB+
15  Paciente P    42       99      1.52          O+
16  Paciente Q    60       82      1.77          A+
17  Paciente R    29       65      1.75          O+
18  Paciente S    60       85      1.68         AB+
19  Paciente T    34       51      1.80          A+

In [31]:
miMascara = (pacientes["Edad"] > 30) | (pacientes["Tipo_Sangre"] == "AB+")
miMascara

0     False
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9     False
10    False
11     True
12    False
13     True
14     True
15     True
16     True
17    False
18     True
19     True
dtype: bool

In [32]:
pacientes[miMascara]["Nombre"]

1     Paciente B
2     Paciente C
3     Paciente D
4     Paciente E
5     Paciente F
6     Paciente G
7     Paciente H
11    Paciente L
13    Paciente N
14    Paciente O
15    Paciente P
16    Paciente Q
18    Paciente S
19    Paciente T
Name: Nombre, dtype: object

In [33]:
pacientes["Peso_kg"] > 70

0     False
1      True
2      True
3     False
4      True
5     False
6     False
7      True
8      True
9      True
10     True
11    False
12    False
13     True
14    False
15     True
16     True
17    False
18     True
19    False
Name: Peso_kg, dtype: bool

In [40]:
# Filtrado Simple peso mayor a 70 kg
pacientes[pacientes["Peso_kg"] > 70]

        Nombre  Edad  Peso_kg  Altura_m Tipo_Sangre
1   Paciente B    41       97      1.67          B-
2   Paciente C    34       86      1.63          O+
4   Paciente E    39       83      1.54          A+
7   Paciente H    49       73      1.56          B-
8   Paciente I    21       97      1.60          A+
9   Paciente J    15      100      1.64          B-
10  Paciente K    23       90      1.57          B-
13  Paciente N    24       79      1.73         AB+
15  Paciente P    42       99      1.52          O+
16  Paciente Q    60       82      1.77          A+
18  Paciente S    60       85      1.68         AB+

In [36]:
pacientes["Tipo_Sangre"] == "AB+"

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14     True
15    False
16    False
17    False
18     True
19    False
Name: Tipo_Sangre, dtype: bool

In [41]:
# Filtrado Simple tipo sangre AB+
pacientes[pacientes["Tipo_Sangre"] == "AB+"]

        Nombre  Edad  Peso_kg  Altura_m Tipo_Sangre
3   Paciente D    21       61      1.78         AB+
6   Paciente G    37       65      1.81         AB+
13  Paciente N    24       79      1.73         AB+
14  Paciente O    54       70      1.86         AB+
18  Paciente S    60       85      1.68         AB+

In [45]:
# Filtrado multiple edad mayor a 18 y tipo de sangre O+
pacientes[(pacientes["Edad"] > 30) & (pacientes["Tipo_Sangre"] == "O+")]

        Nombre  Edad  Peso_kg  Altura_m Tipo_Sangre
2   Paciente C    34       86      1.63          O+
15  Paciente P    42       99      1.52          O+

In [47]:
pacientes.loc[[0, 3, 5], ["Nombre", "Tipo_Sangre"]]

       Nombre Tipo_Sangre
0  Paciente A          B-
3  Paciente D         AB+
5  Paciente F          B-

In [ ]:
pacientes.loc[[0, 3, 5, 10]]

        Nombre  Edad  Peso_kg  Altura_m Tipo_Sangre
0   Paciente A    21       63      1.74          B-
3   Paciente D    21       61      1.78         AB+
5   Paciente F    34       69      1.58          B-
10  Paciente K    23       90      1.57          B-

In [54]:
pacientes.loc[[i for i in range(3, -1, -2)]]

       Nombre  Edad  Peso_kg  Altura_m Tipo_Sangre
3  Paciente D    21       61      1.78         AB+
1  Paciente B    41       97      1.67          B-